setup:
  - sudo systemctl disable apt-daily-upgrade.timer
  - sudo systemctl mask apt-daily-upgrade.service
  - sudo systemctl disable apt-daily.timer
  - sudo systemctl mask apt-daily.service
  - sudo timedatectl set-ntp off
  - sudo timedatectl set-ntp on
  - sleep 1
  - sudo apt-get update
  - sudo apt update
  - sudo apt remove flash-kernel -y
  - sudo apt install python3 -y
  - sudo apt install python3-pip -y
  - sudo apt install docker.io -y
jobs:
  - name: build
    steps:
      - name: download prj
        run: git clone github.com/reljicd/django-blog.git
      - name: install django and other requirements
        run: pip install -r django-blog/requirements.txt 
      - name: edit settings.py
        scriptRun: sed -i "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \[\'"*"\'\]/"  django-blog/mysite/settings.py
      - name: migrate for django
        run: python3 django-blog/manage.py migrate
      - name: load sample data
        run: python3 django-blog/manage.py loaddata users posts comments
      - name: build docker image
        run: sudo docker build -t reljicd/django-blognew -f django-blog/docker/Dockerfile django-blog/ > dockerbuildoutput.txt
      - name: save docker image as tar
        run: sudo docker save -o ~/dockerimage.tar reljicd/django-blognew
      - name: store build output
        shared: ~/dockerimage.tar
  - name: test
    steps:
      - name: run tests after build
        run: python3 django-blog/manage.py test blog > blog-tests.txt
  - name: deploy
    steps:
      - name: save docker image from tar
        run: docker load -i output/dockerimage.tar
      - name: run docker image
        backgroundRun: docker run --rm -i -p 8080:8000 reljicd/django-blognew
  - name: monitor
    steps:
      - name: use this URL for monitoring
        run: /admin

