setup:
  - {package: maven, version: 3.6.3}
  - {package: openjdk-11-jdk, version: 11.0.14}
  - export DEBIAN_FRONTEND="noninteractive" && sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password rootpw" && sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password rootpw" && sudo mkdir -p /etc/mysql/conf.d && sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5 && echo "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-8.0" | sudo tee -a /etc/apt/sources.list.d/mysql.list && sudo apt-get install -y mysql-server
jobs:
  - name: build
    steps:
      - name: download prj
        run: git clone https://spidugu:xxxx@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: create application.yml
        run: cp /home/ubuntu/iTrust2-v10/iTrust2/src/main/resources/application.yml.template /home/ubuntu/iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: edit application.yml
        run: sed -i 's/password:/password:\ rootpw/g' /home/ubuntu/iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: run maven
        run: mvn -f /home/ubuntu/iTrust2-v10/iTrust2 clean test > mvnOutput.txt