setup:
  - sudo apt-get update
  - sudo apt-get remove flash-kernel -y
  - sudo apt-get install nodejs -y
  - sudo apt-get install npm -y
jobs:
  - name: build
    steps:
      - run: git clone github.ncsu.edu/smdupor/AmazeZone.com.git
