setup:
  - sudo apt-get update
jobs:
  - name: build
    steps:
      - name: download prj
        run: git clone github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: create application.yml
        run: cp ~/iTrust2-v10/iTrust2/src/main/resources/application.yml.template ~/iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: edit application.yml
        run: sed -i 's/password:/password:\ rootpw/g' ~/iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: run maven
        run: mvn -f ~/iTrust2-v10/iTrust2 clean test > mvnOutput.txt
      - name: maven package
        run: mvn -f ~/iTrust2-v10/iTrust2 -Dmaven.test.skip=true package > mvndeploy.txt
      - name: copy artifact
        shared: ~/iTrust2-v10/iTrust2/target/iTrust2-10.jar
  - name: mutation-coverage
    mutation:
      url: https://github.com/chrisparnin/checkbox.io-micro-preview
      iterations: 2
      mutationfile: marqdown.js
      snapshots:
      - http://localhost:3000/survey/long.md
      - http://localhost:3000/survey/upload.md
      - http://localhost:3000/survey/survey.md
      - http://localhost:3000/survey/variations.md
  - name: deploy
    steps:
      - name: ls
        backgroundRun: ls
