setup:
  - sudo apt-get update
  - sudo apt-get remove flash-kernel -y
  - sudo apt-get install nodejs -y
  - sudo apt-get install npm -y
jobs:
  - name: build
    steps:
      - run: git clone github.com/mars/heroku-cra-node.git
      - run: npm install --prefix heroku-cra-node
      - run: mkdir -p server
      - run: cp -r heroku-cra-node/server server/
      - run: cp heroku-cra-node/package.json server/
      - shared: server/
      - run: echo NODE_ENV=production > heroku-cra-node/react-ui/.env
      - run: echo PORT=8080 >> heroku-cra-node/react-ui/.env
      - run: npm install --prefix heroku-cra-node/react-ui
      - run: npm run build --prefix heroku-cra-node
      - shared: heroku-cra-node/react-ui/build
  - name: test
    steps:
      - run: git clone github.com/mars/heroku-cra-node.git
      - run: npm --prefix heroku-cra-node/react-ui test -- --watchAll=false
  - name: deploy
    steps:
      - run: touch output/server/.env
      - run: echo NODE_ENV=production > output/server/.env
      - run: echo PORT=8080 >> output/server/.env
      - run: npm install --prefix output/server
      - backgroundRun: node output/server/server
      - run: npm install -g serve
      - backgroundRun: serve -s output/build -l 8080
