setup:
  - sudo apt-get update
  - sudo apt-get remove flash-kernel -y
  - sudo apt-get install nodejs -y
  - sudo apt-get install npm -y
jobs:
  - name: build
    steps:
      - run: git clone github.com/mars/heroku-cra-node.git
      - run: npm install --prefix heroku-cra-node
      - run: npm install --prefix heroku-cra-node/react-ui
      - run: npm run build --prefix heroku-cra-node
      - shared: heroku-cra-node/react-ui/build
  - name: test
    steps:
      - run: git clone github.com/mars/heroku-cra-node.git
      - run: npm --prefix heroku-cra-node/react-ui test -- --watchAll=false
  - name: deploy
    steps:
      - run: npm install -g serve
      - backgroundRun: serve -s output/build -l 8080
